id: P009653
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5657
  title: རྩྭ་ཐང་གི་ཟིན་ཐོ།
  author: ''
  volumes:
    995016ed2e334b91a7aa84944e91fe4a:
      image_group_id: I3CN5659
      title: ''
      volume_number: 1
      total_pages: 431
